/* tslint:disable */
/* eslint-disable */
/**
 * Blueprint api
 * The blueprint API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProfileDto } from './ProfileDto';
import {
  ProfileDtoFromJSON,
  ProfileDtoFromJSONTyped,
  ProfileDtoToJSON,
} from './ProfileDto';

/**
 *
 * @export
 * @interface AdminUpdateUserDto
 */
export interface AdminUpdateUserDto {
  /**
   *
   * @type {string}
   * @memberof AdminUpdateUserDto
   */
  email?: string;
  /**
   *
   * @type {string}
   * @memberof AdminUpdateUserDto
   */
  nickname?: string;
  /**
   *
   * @type {ProfileDto}
   * @memberof AdminUpdateUserDto
   */
  profile?: ProfileDto;
  /**
   *
   * @type {string}
   * @memberof AdminUpdateUserDto
   */
  roles?: AdminUpdateUserDtoRolesEnum;
}

/**
 * @export
 */
export const AdminUpdateUserDtoRolesEnum = {
  Guest: 'guest',
  User: 'user',
  Moderator: 'moderator',
  Admin: 'admin',
} as const;
export type AdminUpdateUserDtoRolesEnum =
  (typeof AdminUpdateUserDtoRolesEnum)[keyof typeof AdminUpdateUserDtoRolesEnum];

/**
 * Check if a given object implements the AdminUpdateUserDto interface.
 */
export function instanceOfAdminUpdateUserDto(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function AdminUpdateUserDtoFromJSON(json: any): AdminUpdateUserDto {
  return AdminUpdateUserDtoFromJSONTyped(json, false);
}

export function AdminUpdateUserDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AdminUpdateUserDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    email: !exists(json, 'email') ? undefined : json['email'],
    nickname: !exists(json, 'nickname') ? undefined : json['nickname'],
    profile: !exists(json, 'profile')
      ? undefined
      : ProfileDtoFromJSON(json['profile']),
    roles: !exists(json, 'roles') ? undefined : json['roles'],
  };
}

export function AdminUpdateUserDtoToJSON(
  value?: AdminUpdateUserDto | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    email: value.email,
    nickname: value.nickname,
    profile: ProfileDtoToJSON(value.profile),
    roles: value.roles,
  };
}
