/* tslint:disable */
/* eslint-disable */
/**
 * Blueprint api
 * The blueprint API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProfileDto } from './ProfileDto';
import {
    ProfileDtoFromJSON,
    ProfileDtoFromJSONTyped,
    ProfileDtoToJSON,
} from './ProfileDto';

/**
 * 
 * @export
 * @interface AdminUpdateUserBodyDto
 */
export interface AdminUpdateUserBodyDto {
    /**
     * 
     * @type {string}
     * @memberof AdminUpdateUserBodyDto
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof AdminUpdateUserBodyDto
     */
    nickname?: string;
    /**
     * 
     * @type {ProfileDto}
     * @memberof AdminUpdateUserBodyDto
     */
    profile: ProfileDto;
    /**
     * 
     * @type {string}
     * @memberof AdminUpdateUserBodyDto
     */
    roles?: AdminUpdateUserBodyDtoRolesEnum;
}


/**
 * @export
 */
export const AdminUpdateUserBodyDtoRolesEnum = {
    Guest: 'guest',
    User: 'user',
    Moderator: 'moderator',
    Admin: 'admin'
} as const;
export type AdminUpdateUserBodyDtoRolesEnum = typeof AdminUpdateUserBodyDtoRolesEnum[keyof typeof AdminUpdateUserBodyDtoRolesEnum];


/**
 * Check if a given object implements the AdminUpdateUserBodyDto interface.
 */
export function instanceOfAdminUpdateUserBodyDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "profile" in value;

    return isInstance;
}

export function AdminUpdateUserBodyDtoFromJSON(json: any): AdminUpdateUserBodyDto {
    return AdminUpdateUserBodyDtoFromJSONTyped(json, false);
}

export function AdminUpdateUserBodyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminUpdateUserBodyDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': !exists(json, 'email') ? undefined : json['email'],
        'nickname': !exists(json, 'nickname') ? undefined : json['nickname'],
        'profile': ProfileDtoFromJSON(json['profile']),
        'roles': !exists(json, 'roles') ? undefined : json['roles'],
    };
}

export function AdminUpdateUserBodyDtoToJSON(value?: AdminUpdateUserBodyDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'nickname': value.nickname,
        'profile': ProfileDtoToJSON(value.profile),
        'roles': value.roles,
    };
}

