/* tslint:disable */
/* eslint-disable */
/**
 * Blueprint api
 * The blueprint API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthControllerRefreshRequest
 */
export interface AuthControllerRefreshRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthControllerRefreshRequest
     */
    refreshToken?: string;
}

/**
 * Check if a given object implements the AuthControllerRefreshRequest interface.
 */
export function instanceOfAuthControllerRefreshRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthControllerRefreshRequestFromJSON(json: any): AuthControllerRefreshRequest {
    return AuthControllerRefreshRequestFromJSONTyped(json, false);
}

export function AuthControllerRefreshRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthControllerRefreshRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'refreshToken': !exists(json, 'refreshToken') ? undefined : json['refreshToken'],
    };
}

export function AuthControllerRefreshRequestToJSON(value?: AuthControllerRefreshRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'refreshToken': value.refreshToken,
    };
}

