/* tslint:disable */
/* eslint-disable */
/**
 * Blueprint api
 * The blueprint API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ForgottenPasswordDto
 */
export interface ForgottenPasswordDto {
    /**
     * Token for reset password
     * @type {string}
     * @memberof ForgottenPasswordDto
     */
    token: string;
}

/**
 * Check if a given object implements the ForgottenPasswordDto interface.
 */
export function instanceOfForgottenPasswordDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "token" in value;

    return isInstance;
}

export function ForgottenPasswordDtoFromJSON(json: any): ForgottenPasswordDto {
    return ForgottenPasswordDtoFromJSONTyped(json, false);
}

export function ForgottenPasswordDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForgottenPasswordDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function ForgottenPasswordDtoToJSON(value?: ForgottenPasswordDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
    };
}

