/* tslint:disable */
/* eslint-disable */
/**
 * Blueprint api
 * The blueprint API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginByEmail
 */
export interface LoginByEmail {
    /**
     * 
     * @type {string}
     * @memberof LoginByEmail
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof LoginByEmail
     */
    password: string;
    /**
     * 
     * @type {boolean}
     * @memberof LoginByEmail
     */
    rememberMe?: boolean;
}

/**
 * Check if a given object implements the LoginByEmail interface.
 */
export function instanceOfLoginByEmail(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function LoginByEmailFromJSON(json: any): LoginByEmail {
    return LoginByEmailFromJSONTyped(json, false);
}

export function LoginByEmailFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginByEmail {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'rememberMe': !exists(json, 'rememberMe') ? undefined : json['rememberMe'],
    };
}

export function LoginByEmailToJSON(value?: LoginByEmail | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'password': value.password,
        'rememberMe': value.rememberMe,
    };
}

