/* tslint:disable */
/* eslint-disable */
/**
 * Blueprint api
 * The blueprint API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProfileDto
 */
export interface ProfileDto {
    /**
     * User name
     * @type {string}
     * @memberof ProfileDto
     */
    name?: string;
    /**
     * User birthday
     * @type {Date}
     * @memberof ProfileDto
     */
    birthday?: Date;
    /**
     * Profile url link
     * @type {string}
     * @memberof ProfileDto
     */
    photoUrl?: string;
}

/**
 * Check if a given object implements the ProfileDto interface.
 */
export function instanceOfProfileDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProfileDtoFromJSON(json: any): ProfileDto {
    return ProfileDtoFromJSONTyped(json, false);
}

export function ProfileDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'birthday': !exists(json, 'birthday') ? undefined : (new Date(json['birthday'])),
        'photoUrl': !exists(json, 'photoUrl') ? undefined : json['photoUrl'],
    };
}

export function ProfileDtoToJSON(value?: ProfileDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'birthday': value.birthday === undefined ? undefined : (value.birthday.toISOString()),
        'photoUrl': value.photoUrl,
    };
}

