/* tslint:disable */
/* eslint-disable */
/**
 * Blueprint api
 * The blueprint API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ProfileDto
 */
export interface ProfileDto {
  /**
   *
   * @type {string}
   * @memberof ProfileDto
   */
  name: string;
  /**
   *
   * @type {Date}
   * @memberof ProfileDto
   */
  birthday: Date;
  /**
   *
   * @type {string}
   * @memberof ProfileDto
   */
  photoUrl: string;
  /**
   *
   * @type {string}
   * @memberof ProfileDto
   */
  userId: string;
}

/**
 * Check if a given object implements the ProfileDto interface.
 */
export function instanceOfProfileDto(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'name' in value;
  isInstance = isInstance && 'birthday' in value;
  isInstance = isInstance && 'photoUrl' in value;
  isInstance = isInstance && 'userId' in value;

  return isInstance;
}

export function ProfileDtoFromJSON(json: any): ProfileDto {
  return ProfileDtoFromJSONTyped(json, false);
}

export function ProfileDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ProfileDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: json['name'],
    birthday: new Date(json['birthday']),
    photoUrl: json['photoUrl'],
    userId: json['userId'],
  };
}

export function ProfileDtoToJSON(value?: ProfileDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    birthday: value.birthday.toISOString(),
    photoUrl: value.photoUrl,
    userId: value.userId,
  };
}
