/* tslint:disable */
/* eslint-disable */
/**
 * Blueprint api
 * The blueprint API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RefreshTokenDto
 */
export interface RefreshTokenDto {
    /**
     * The refresh token issued to the client
     * @type {string}
     * @memberof RefreshTokenDto
     */
    refreshToken: string;
}

/**
 * Check if a given object implements the RefreshTokenDto interface.
 */
export function instanceOfRefreshTokenDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "refreshToken" in value;

    return isInstance;
}

export function RefreshTokenDtoFromJSON(json: any): RefreshTokenDto {
    return RefreshTokenDtoFromJSONTyped(json, false);
}

export function RefreshTokenDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefreshTokenDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'refreshToken': json['refreshToken'],
    };
}

export function RefreshTokenDtoToJSON(value?: RefreshTokenDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'refreshToken': value.refreshToken,
    };
}

