/* tslint:disable */
/* eslint-disable */
/**
 * Blueprint api
 * The blueprint API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TokenValidationPayload } from './TokenValidationPayload';
import {
    TokenValidationPayloadFromJSON,
    TokenValidationPayloadFromJSONTyped,
    TokenValidationPayloadToJSON,
} from './TokenValidationPayload';

/**
 * 
 * @export
 * @interface TokenValidationErrorDto
 */
export interface TokenValidationErrorDto {
    /**
     * 
     * @type {string}
     * @memberof TokenValidationErrorDto
     */
    message: string;
    /**
     * 
     * @type {TokenValidationPayload}
     * @memberof TokenValidationErrorDto
     */
    payload: TokenValidationPayload;
}

/**
 * Check if a given object implements the TokenValidationErrorDto interface.
 */
export function instanceOfTokenValidationErrorDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;
    isInstance = isInstance && "payload" in value;

    return isInstance;
}

export function TokenValidationErrorDtoFromJSON(json: any): TokenValidationErrorDto {
    return TokenValidationErrorDtoFromJSONTyped(json, false);
}

export function TokenValidationErrorDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenValidationErrorDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'payload': TokenValidationPayloadFromJSON(json['payload']),
    };
}

export function TokenValidationErrorDtoToJSON(value?: TokenValidationErrorDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'payload': TokenValidationPayloadToJSON(value.payload),
    };
}

