/* tslint:disable */
/* eslint-disable */
/**
 * Blueprint api
 * The blueprint API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface TokenValidationPayload
 */
export interface TokenValidationPayload {
  /**
   * Time before unlock next attempt in Unix time.
   * @type {number}
   * @memberof TokenValidationPayload
   */
  unlockTime: number;
}

/**
 * Check if a given object implements the TokenValidationPayload interface.
 */
export function instanceOfTokenValidationPayload(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'unlockTime' in value;

  return isInstance;
}

export function TokenValidationPayloadFromJSON(
  json: any
): TokenValidationPayload {
  return TokenValidationPayloadFromJSONTyped(json, false);
}

export function TokenValidationPayloadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): TokenValidationPayload {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    unlockTime: json['unlockTime'],
  };
}

export function TokenValidationPayloadToJSON(
  value?: TokenValidationPayload | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    unlockTime: value.unlockTime,
  };
}
