/* tslint:disable */
/* eslint-disable */
/**
 * Blueprint api
 * The blueprint API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProfileDto } from './ProfileDto';
import {
  ProfileDtoFromJSON,
  ProfileDtoFromJSONTyped,
  ProfileDtoToJSON,
} from './ProfileDto';

/**
 *
 * @export
 * @interface UpdateUserBodyDto
 */
export interface UpdateUserBodyDto {
  /**
   *
   * @type {string}
   * @memberof UpdateUserBodyDto
   */
  email?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateUserBodyDto
   */
  nickname?: string;
  /**
   *
   * @type {ProfileDto}
   * @memberof UpdateUserBodyDto
   */
  profile?: ProfileDto;
}

/**
 * Check if a given object implements the UpdateUserBodyDto interface.
 */
export function instanceOfUpdateUserBodyDto(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function UpdateUserBodyDtoFromJSON(json: any): UpdateUserBodyDto {
  return UpdateUserBodyDtoFromJSONTyped(json, false);
}

export function UpdateUserBodyDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UpdateUserBodyDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    email: !exists(json, 'email') ? undefined : json['email'],
    nickname: !exists(json, 'nickname') ? undefined : json['nickname'],
    profile: !exists(json, 'profile')
      ? undefined
      : ProfileDtoFromJSON(json['profile']),
  };
}

export function UpdateUserBodyDtoToJSON(value?: UpdateUserBodyDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    email: value.email,
    nickname: value.nickname,
    profile: ProfileDtoToJSON(value.profile),
  };
}
